VocabPBT/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'word.views.login_page', name='login_page'),
    url(r'^login/$', 'word.views.login', name='login'),
    url(r'^register/$', 'word.views.register', name='register'),
    url(r'^add/$', 'word.views.add_word', name='add'),
    url(r'^show/$', 'word.views.show_word', name='show'),
    url(r'serch/(\w+)/$', 'word.views.serch', name='serch'),
    url(r'game/$', 'word.views.game', name='game'),
    url(r'^logout/$', 'word.views.logout', name='logout'),
    url(r'^sentence/(\w+)/$', 'word.views.sentence_word', name='sentence'),
)

ass2/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'word.views.login_page', name='login_page'),
    url(r'^login/$', 'word.views.login', name='login'),
    url(r'^register/$', 'word.views.register', name='register'),
    url(r'^add/$', 'word.views.add_word', name='add'),
    url(r'^show/$', 'word.views.show_word', name='show'),
    url(r'serch/(\w+)/$', 'word.views.serch', name='serch'),
    url(r'game/$', 'word.views.game', name='game'),
    url(r'^logout/$', 'word.views.logout', name='logout'),
    url(r'^sentence/(\w+)/$', 'word.views.sentence_word', name='sentence'),
)

word/models.py
from django.db import models

class Vocab(models.Model):
    word = models.TextField(default='')
    mean = models.TextField(default='')
    add_date = models.TextField(default='')
    # เพิ่ม url, add_date

class Sentence(models.Model):
    vocab = models.ForeignKey(Vocab)
    example = models.TextField(default='')
    url = models.TextField(default='')

class User(models.Model):
    username = models.TextField(default='')
    password = models.TextField(default='')
    birthday = models.TextField(default='')
    email = models.TextField(default='')

word/views.py
#!/usr/bin/python
from django.shortcuts import redirect, render
from word.models import Vocab, User, Sentence
from random import randint
from datetime import date
from django.http import HttpResponse
import operator
count, width, height = 15, 20, 14

class wordplay:
    blue = 0
    def __init__(self, ch, posX, posY, isAns):
        self.ch = ch
        self.posX = posX
        self.posY = posY
        self.isAns = isAns

    def setblue(self):
        self.blue = 1

def add_list(word):
    list_word = []
    list_word_row = []
    for w in word:
        list_word.append(w.word)
        list_word.append(w.mean)
        list_word.append(w.word)
        list_word_row.append(list_word)
        list_word = []
    return sorted(list_word_row)

def login_page(request):
    if request.session.get('user_session', '') != '':
        return redirect('/add')
    return render(request, 'login.html')

def show_word(request):
    if request.session.get('user_session', '') == '':
        return render(
                      request,
                      'link_text.html',
                      {'title_text':"not member",
                       'text1':"You are not member",
                       'data_send':"",
                       'text2':"",
                       'link_text':"go back"
                       })
    if request.method == 'POST' and request.POST.get('sentence','') == 'sentence':
        word = request.POST['id_sentence']
        return redirect('/sentence/%s/' %word)
    words = Vocab.objects.all()
    list_ = add_list(words)
    return render(request, 'show_word.html', {'words': list_ ,'user': request.session['user_session']})

def add_word(request):
    if request.session.get('user_session', '') == '':
        return render(
                      request,
                      'link_text.html',
                      {'title_text':"not member",
                       'text1':"You are not member",
                       'data_send':"",
                       'text2':"",
                       'link_text':"go back"
                       })
    if request.method == 'POST' and request.POST.get('serch','') == 'serch':
        word_serch = request.POST['word_serch']
        if(word_serch == ''):
            return redirect('/serch/null')
        return redirect('/serch/%s/' %word_serch)
    if request.method == 'POST' and request.POST.get('send','') == 'send':
        word_text = request.POST['word_text']
        mean_text = request.POST['mean_text']
        words = Vocab.objects.all()
        for w_c in words :
            if(w_c.word == word_text):
                    return render(request, 'add_word.html', {'text':"this word have in table", 'user': request.session['user_session']})
        Vocab.objects.create(
            word = word_text,
            mean = mean_text,
            )
        return redirect('/show')
    return render(request, 'add_word.html', {'text' : "", 'user': request.session['user_session']})

def serch(request , word_find):
    if request.session.get('user_session', '') == '':
        return render(
                      request,
                      'link_text.html',
                      {'title_text':"not member",
                       'text1':"You are not member",
                       'data_send':"",
                       'text2':"",
                       'link_text':"go back"
                       })
    if request.method == 'POST' and request.POST.get('sentence','') == 'sentence':
        word = request.POST['id_sentence']
        return redirect('/sentence/%s/' %word)
    words = Vocab.objects.all()
    list_word =[]
    list_word_row = []
    for w in words:
        if(word_find in w.word):
            list_word.append(w.word)
            list_word.append(w.mean)
            list_word.append(w.word)
            list_word_row.append(list_word)
            list_word = []
    list_=sorted(list_word_row)
    return render(request, 'show_word.html', {'words':list_,'user': request.session['user_session']})

def sentence_word(request , word_send):
    if request.session.get('user_session', '') == '':
        return render(
                      request,
                      'link_text.html',
                      {'title_text':"not member",
                       'text1':"You are not member",
                       'data_send':"",
                       'text2':"",
                       'link_text':"go back"
                       })
    vocab_ = Vocab.objects.get(word=word_send)
    if request.method == 'POST' and request.POST.get('send','') == 'send':
        example_text = request.POST['example_text']
        url_text = request.POST['url_text']
        Sentence.objects.create(
            vocab = vocab_,
            example = example_text,
            url = url_text,
            )
        return redirect('/sentence/%s/' %word_send)
    return render(request, 'sentence.html', {'vocab':vocab_,'word':vocab_.word,'mean':vocab_.mean,'user': request.session['user_session']})

def game(request):
    if request.session.get('user_session', '') == '':
        return render(
                      request,
                      'link_text.html',
                      {'title_text':"not member",
                       'text1':"You are not member",
                       'data_send':"",
                       'text2':"",
                       'link_text':"go back"
                       })
    if request.method == "POST":
        rows = request.POST.get('platform', '')
        platform = [[wordplay(char.split(',')[0], int(char.split(',')[1]), int(char.split(',')[2]), int(char.split(',')[3])) for char in row.split(')') if char != ''] for row in rows.split('/') if row != '']
        queststr, finish = request.POST['quest'], 'no'
        meanstr = request.POST['mean']
        quest = [i for i in queststr.split(',') if i != '']
        mean = [i for i in meanstr.split(',') if i != '']
        type = request.POST['type']
        if request.POST["val"] == '': type = 'reset'
        if type == 'submit':
            if request.POST["val"] in quest:
                for q in range(len(quest)):
                    if quest[q] == request.POST["val"]:
                        if len(quest) == 1:
                            finish = 'yes'
                        quest.pop(q)
                        mean.pop(q)
                        break
                for row in request.POST['position'].split(','):
                    if row != '':
                        pos = row.split('_')
                        platform[int(pos[1])][int(pos[0])].isAns = 2
            print(quest)
            ###increase score###
            return render(request, 'wordhunt.html', {
                   'rows':platform,
                   'cheat':request.POST['cheat'],
                   'user':request.session.get('user_session', ''),
                   'fin':finish,
                   'quest':quest,
                   'mean':mean,
            })
        elif type == 'reset':
            select = ''
            try:
                platform[int(request.POST['val'].split('_')[1])][int(request.POST['val'].split('_')[0])].setblue()
                select = (request.POST['val'] == '') and '' or platform[int(request.POST['val'].split('_')[1])][int(request.POST['val'].split('_')[0])]
            except: pass
            return render(request, 'wordhunt.html', {
                   'rows':platform,
                   'selected':select,
                   'cheat':(request.POST['cheat'] == 'yes') and 'yes' or 'no',
                   'user':request.session.get('user_session', ''),
                   'quest':quest,
                   'mean':mean,
               })
    if Vocab.objects.count() >= count:
        words, means, choose, mean = [""]*Vocab.objects.count(), [""]*Vocab.objects.count(), [""]*count, [""]*count
        k = 0
        for word in Vocab.objects.all():
            words[k] = word.word
            means[k] = word.mean
            k += 1
        k = 0
        for i in range(count):
            while k < count:
                try:
                    ran = randint(0, Vocab.objects.count())
                    if not words[ran] in choose:
                        choose[k] = words[ran]
                        mean[k] = means[ran]
                        k += 1
                except:pass
        while 1:
            success = 0
            chars = [['' for j in range(width)] for i in range(height)]
            for i in range(count):
                for z in range(30):
                    try:
                        dx = randint(-1, 1)
                        dy = (dx == 0) and (randint(0, 1)*2)-1 or randint(-1, 1)
                        startx = randint(0, width-1)
                        starty = randint(0, height-1)
                        avail = 1
                        for j in range(len(choose[i])):
                            if chars[starty + (dy*j)][startx + (dx*j)] != '' or\
                               startx + (dx*j) >=width or\
                               startx + (dx*j) < 0 or\
                               starty + (dy*j) >= height or\
                               starty + (dy*j) < 0:
                                avail = 0
                        if avail:
                            for j in range(len(choose[i])):
                                chars[starty + (dy*j)][startx + (dx*j)] = choose[i][j]
                            success += 1
                            break
                    except: pass
            if success == count:break
            
        disp = [[(chars[j][i] == '') and wordplay(chr(randint(0, 25) + 97),i, j, 0) or wordplay(chars[j][i], i, j, 1) for i in range(width)] for j in range(height)]
        return render(request, 'wordhunt.html', {
                   'rows':disp,
                   'user':request.session.get('user_session', ''),
                   'quest':choose,
                   'mean':mean,
               })
                        

word/templates/add_word.html
<html>
    <head>
        <title>add</title>
    </head>
    <style type="text/css">
        body {background-image: url("http://cdn1.bigcommerce.com/server5200/1ee3c/products/283/images/363/Blackboard_Doodles_Wallpaper__19219.1405428766.1200.1200.jpg?c=2");}
        #header {
            background-image: url("http://i687.photobucket.com/albums/vv237/4-one/4-1/HT2/nbbn7.png");
            background-repeat: no-repeat;
            background-position: center top;
            background-size:35% 90%;            
            text-align: center;
            font-size:25px;
            color:black;
            padding:4%;
        }
        #body{
            background-image: url("http://i687.photobucket.com/albums/vv237/4-one/4-1/HT/KFZ-i3.png");
            background-repeat: no-repeat;
            background-position: center top;
            background-size:35% 100%;
            text-align: center;
            color:white;
            padding:4%;
        }
    </style>
    <body>
        <div id=header>
        <h1>dictionary</h1>
        </div>
        <div id =body> 
        <b>welcome</b> {{ user }} <input type="button" value="logout" id="logout" onclick='javascript:window.location.href="/logout"'><br />
        <input type="button" value ="Vocabulary" id="vocab" onclick='javascript:window.location.href="/show"'> 
        <input type="button" value ="Game" id="game" onclick='javascript:window.location.href="/game"'> 
        <FORM method="POST">
	   <b>คำ</b>
           <br>
           <input name="word_text" id="word_new"/>
           <br>
           <b>ความหมาย</b>
           <br>
           <input name="mean_text" id="mean_new"/>
           <br>
            <INPUT Type="submit" VALUE="enter" id="button" >
            <INPUT Type = "hidden" value ="send" name = 'send'>
            {% csrf_token %}
       </FORM>

       {{ text }}

       <FORM method="POST">
	   <b>ค้นหา คำ</b>
           <br>
           <input name="word_serch" id="word_serch_new"/>
           <br>
           <INPUT Type="submit" VALUE="enter" id="button_serch" >
           <INPUT Type = "hidden" value ="serch" name = 'serch'>
           {% csrf_token %}
       </FORM>
       </div>        
    </body>
</html>

word/templates/link_text.html
<html>
    <head>
    <style type="text/css">
        body {background-image: url("http://cdn1.bigcommerce.com/server5200/1ee3c/products/283/images/363/Blackboard_Doodles_Wallpaper__19219.1405428766.1200.1200.jpg?c=2");}
        #body{
            background-image: url("http://i687.photobucket.com/albums/vv237/4-one/4-1/HT/KFZ-i3.png");
            background-repeat: no-repeat;
            background-position: center top;
            text-align: center;
            font-size:20px;
            color:white;
            padding:10%;
        }
    </style>
        <title>
            {{title_text}}
        </title>
    </head>
    <body>
        <div id=body><b>
        {{text1}} {{data_send}} <br>{{text2}} 
        <a href="/">
            {{link_text}}
        </a>
        </b>
        </div> 
    </body>
</html>

word/templates/login.html
<!DOCTYPE html>
<script>
function checkblank(){
    var token = ['user', 'pass'], pass = true;
    for(var i = 0; i < token.length; i++){
        if(document.getElementById("id_"+token[i]).value == ""){
            document.getElementById(token[i]+"blank").innerHTML = '<font color="red">'+token[i]+' must not blank</font>';
            pass = false;
        }else{
            document.getElementById(token[i]+"blank").innerHTML = '';
        }
    }
    if(pass){
        document.getElementById('loginform').submit();
    }
}
</script>
<html>
    <head>
        <title>Login</title>
    </head>
    <style type="text/css">
        body {background-image: url("http://cdn1.bigcommerce.com/server5200/1ee3c/products/283/images/363/Blackboard_Doodles_Wallpaper__19219.1405428766.1200.1200.jpg?c=2");}
        #header {
            background-image: url("http://i687.photobucket.com/albums/vv237/4-one/4-1/HT2/nbbn7.png");
            background-repeat: no-repeat;
            background-position: center top;
            background-size:35% 90%;            
            text-align: center;
            font-size:25px;
            color:black;
            padding:4%;
        }
        #body{
            background-image: url("http://i687.photobucket.com/albums/vv237/4-one/4-1/HT/KFZ-i3.png");
            background-repeat: no-repeat;
            background-position: center top;
            text-align: center;
            color:white;
            padding:7%;
        }
    </style>
    <body>
        <div id=header>
        <h1>Login</h1>
        </div>
        <div id=body> 
        <FORM method="POST" action="/login/" id="loginform">
	    <b>Username</b>
            <input name="user" id="id_user"/><span id="userblank"></span>
            <br>
            <b>Password </b>
            <input type="password" name="pass" id="id_pass"/><span id="passblank"></span>
            <br> 
            <INPUT Type="button" VALUE="Login" id="button_login" onclick="javascript:checkblank()">
            <INPUT Type = "hidden" value ="login" name = 'login'>
            {% csrf_token %}
        </FORM>
        <input type="button" value ="Register" id="register" onclick='javascript:window.location.href="/register"'>
        </div>  
    </body>
</html>

word/templates/register.html
<html>
<script>
function checkdata(){
    var keys = ["user", "pass", "birth", "email"], pass = true;
    for(var i in keys){
        if(document.getElementById(keys[i]).value == ""){
            document.getElementById(keys[i]+"blank").innerHTML = "<font color='red'>"+keys[i]+" is empty**</font>";
            pass = false;
        }else{
             document.getElementById(keys[i]+"blank").innerHTML = "";
        }
    }
    if(pass == true){
        document.regisform.submit();
    }
}
</script>
<head>
    <title>Register</title>
    <style type="text/css">
        body {background-image: url("http://cdn1.bigcommerce.com/server5200/1ee3c/products/283/images/363/Blackboard_Doodles_Wallpaper__19219.1405428766.1200.1200.jpg?c=2");}
        #header {
            background-image: url("http://i687.photobucket.com/albums/vv237/4-one/4-1/HT2/nbbn7.png");
            background-repeat: no-repeat;
            background-position: center top;
            background-size:35% 90%;            
            text-align: center;
            font-size:25px;
            color:black;
            padding:4%;
        }
        #body{
            background-image: url("http://i687.photobucket.com/albums/vv237/4-one/4-1/HT/KFZ-i3.png");
            background-repeat: no-repeat;
            background-position: center top;
            text-align: center;
            color:white;
            padding:5%;
        }
    </style>
    <div id= header>
    <h1 style="text-align:center;">Register</h1>
    </div>
</head>
<body>
<div id=body>
<form id="regisform" name="regisform" method="POST">
<b>Username </b> <input id="user" name="user" placeholder="Username"><span id="userblank">{% if fail == 'user' %}This Username is exists{% endif %}</span><br />
<b>Password </b><input type="password" id="pass" name="pass" placeholder="Password"><span id="passblank"></span><br />
<b>Birthday </b><input id="birth" name="birth" placeholder="Birthday"><span id="birthblank"></span><br />
<b>Email </b><input id="email" name="email" placeholder="Email"><span id="emailblank"></span><br />
<input type="button" id="send" name="send" value="Register" onclick="javascript:checkdata()">
{% csrf_token %}
</form>
</div>
</body>
</html>

word/templates/sentence.html
<html>
    <head>
        <title>show sentence</title>
    </head>
    <style type="text/css">
        body {background-image: url("http://cdn1.bigcommerce.com/server5200/1ee3c/products/283/images/363/Blackboard_Doodles_Wallpaper__19219.1405428766.1200.1200.jpg?c=2");}
        #header {
            background-image: url("http://i687.photobucket.com/albums/vv237/4-one/4-1/HT2/nbbn7.png");
            background-repeat: no-repeat;
            background-position: center top;
            background-size:35% 90%;            
            text-align: center;
            font-size:25px;
            color:black;
            padding:4%;
        }
        #body{
            background-image: url("http://i687.photobucket.com/albums/vv237/4-one/4-1/HT/KFZ-i3.png");
            background-repeat: no-repeat;
            background-position: center top;
            background-size:35% 100%;
            text-align: center;
            color:white;
            padding:2%;
        }
    </style>
    <body>
        <div id=header>
        <h1>sentence</h1>
        </div>
        <div id=body>
        <b>welcome</b> {{ user }} <input type="button" value="logout" onclick='javascript:window.location.href="/logout"'><br />
        <input type="button" value ="Vocabulary" onclick='javascript:window.location.href="/show"'>
        <input type="button" value ="Add Vocabulary" onclick='javascript:window.location.href="/add"'>  
        <input type="button" value ="Game" onclick='javascript:window.location.href="/game"'>  
        <br>
        <b>คำ :</b> {{word}} 
        <br>
        <b>ความหมาย :</b> {{mean}}
       <FORM method="POST">
	   ตัวอย่างประโยค
           <br>
           <input name="example_text" id="example_new"/>
           <br>
                แหล่งที่มา
           <br>
           <input name="url_text" id="url_new"/>
           <br>
            <INPUT Type="submit" VALUE="enter" id="button" >
            <INPUT Type = "hidden" value ="send" name = 'send'>
            {% csrf_token %}
       </FORM>
       </div>
       <br></br>        
       <table bgcolor=white align="center" id="id_list_table" border=1>
             {% for s in vocab.sentence_set.all %}
                 <tr>             
                         <td>{{ s.example }}</td>
                         <td><a href="{{ s.url }}">{{ s.url }}</a></td>
                 </tr>               
            {% endfor %}
        </table>       
    </body>
</html>

word/templates/show_word.html
<html>
    <head>
        <title>show</title>
    </head>
    <style type="text/css">
        body {background-image: url("http://cdn1.bigcommerce.com/server5200/1ee3c/products/283/images/363/Blackboard_Doodles_Wallpaper__19219.1405428766.1200.1200.jpg?c=2");}
        #header {
            background-image: url("http://i687.photobucket.com/albums/vv237/4-one/4-1/HT2/nbbn7.png");
            background-repeat: no-repeat;
            background-position: center top;
            background-size:35% 90%;            
            text-align: center;
            font-size:25px;
            color:black;
            padding:4%;
        }
        #body{
            background-image: url("http://i687.photobucket.com/albums/vv237/4-one/4-1/HT/KFZ-i3.png");
            background-repeat: no-repeat;
            background-position: center top;
            text-align: center;
            background-size:35% 100%;
            color:white;
            padding:2%;
        }
    </style>
    <body>
        <div id=header>
        <h1>Vocabulary</h1>
        </div>
        <div id=body>
        welcome {{ user }} <input type="button" value="logout" id="logout" onclick='javascript:window.location.href="/logout"'><br />
        <input type="button" value ="Add Vocabulary" id="add" onclick='javascript:window.location.href="/add"'>  
        <input type="button" value ="Game" id="game" onclick='javascript:window.location.href="/game"'>
        </div>  
        <br></br>
        <table bgcolor=white align="center"  id="id_list_table" border=1>
             {% for word in words %}
                 <tr>
                 {% for w in word %}
                     {% if forloop.counter < 3 %}                 
                         <td>{{ w }}</td>
                     {% elif forloop.counter < 4 %}
                         <td>
                     <FORM method="POST">
                     <INPUT Type="submit" VALUE="sentence" id="button_s" >      
                     <INPUT Type = "hidden" value ="sentence" name = 'sentence'>
                     <INPUT Type = "hidden" value ="{{ w }}" name = 'id_sentence'>
                     {% csrf_token %}
                 </FORM>
                     </td>
                 {% endif %}
                 {% endfor %}                
            {% endfor %}
        </table>
  </body>
</html>

word/templates/wordhunt.html
<html>
<script src="/home/galible/jquery-2.0.3.js"></script>
<script>
var values = "{% if selected != '' %}{{selected.posX}}_{{selected.posY}},{% endif %}";
function check(pos, ch){
    var position = pos.split("_");
    var itemshow = document.getElementById("showword");
    var itemsend = document.getElementById("val");
    var button = document.getElementById("p_"+position[0]+"_"+position[1]);
    if(values == ""){
        values = pos + ",";
        itemshow.innerHTML += ch;
        button.innerHTML = "<input style=\"color: #0000FF\" "+button.innerHTML.split("input")[1];
        itemsend.value += ch
    }else if(values.split(",").length == 2){
        var valX = values.split(",")[0].split("_")[0];
        var valY = values.split(",")[0].split("_")[1];
        if(Math.abs(parseInt(valX) - parseInt(position[0])) <= 1 && Math.abs(parseInt(valY) - parseInt(position[1])) <= 1 && !(parseInt(valX) == parseInt(position[0]) && parseInt(valY) == parseInt(position[1]))){
            values += pos + ",";
            itemshow.innerHTML += ch;
            button.innerHTML = "<input style=\"color: #0000FF\" "+button.innerHTML.split("input")[1];
            itemsend.value += ch
        }else{
            itemsend.value = pos
            document.getElementById("type").value="reset";
            document.getElementById("submitform").submit();
        }
    }else{
        var len = values.split(",").length - 1;
        var firstX = parseInt(values.split(",")[0].split("_")[0]);
        var firstY = parseInt(values.split(",")[0].split("_")[1]);
        var secondX = parseInt(values.split(",")[1].split("_")[0]);
        var secondY = parseInt(values.split(",")[1].split("_")[1]);
        var dX = secondX - firstX;
        var dY = secondY - firstY;
        var posX = parseInt(position[0]);
        var posY = parseInt(position[1]);
        if(posX == firstX + (dX*len) && posY == firstY + (dY*len)){
            values += pos + ",";
            itemshow.innerHTML += ch;
            button.innerHTML = "<input style=\"color: #0000FF\" "+button.innerHTML.split("input")[1];
            itemsend.value += ch
        }else{
            itemsend.value = pos
            document.getElementById("type").value="reset";
            document.getElementById("submitform").submit();
        }
    }
}
</script>
<head>
    <title>Word Hunt !!</title>
    <div id=header>
    <h1>Game</h1>
    </div>
</head>
<style type="text/css">
        body {background-image: url("http://cdn1.bigcommerce.com/server5200/1ee3c/products/283/images/363/Blackboard_Doodles_Wallpaper__19219.1405428766.1200.1200.jpg?c=2");}
        #header {
            background-image: url("http://i687.photobucket.com/albums/vv237/4-one/4-1/HT2/nbbn7.png");
            background-repeat: no-repeat;
            background-position: center top;
            background-size:35% 90%;            
            text-align: center;
            font-size:25px;
            color:black;
            padding:4%;
        }
        #body{
            background-image: url("http://i687.photobucket.com/albums/vv237/4-one/4-1/HT/KFZ-i3.png");
            background-repeat: no-repeat;
            background-position: center top;
            {%if error == "less15" %}
            background-size:35% 90%;
            {%else%}
            background-size:100% 100%;
            {%endif%}  
            text-align: center;
            color:white;
            padding:6%;
        }
    </style>
<body>
<div id=body>
    <p>
        <b>Welcome</b> {% if user != '' %}{{user}} (<a href='/logout'>logout</a>) {% else %}guest{% endif %} <b>to Word hunt !</b><br>   
        <input type="button" value="Add vocabulary" id="addword" onclick='javascript:window.location.href="/add"'>
        <input type="button" value ="Game" id="game" onclick='javascript:window.location.href="/game"'>
{%if error == "less15" %}
<p>your words are less than 15 <br> please add words up to 15 or more</p>
{% endif %} 
    </p><br/>
       
{% if fin == 'yes' %}
<h1><font color="red">congratulation !! ... You are victorious</font></h1>
{% elif error != "less15" %}
    <table bgcolor=white id="questtable" border="1">
        <tr><td>Your quest : </td>
            {% for word in mean %}
                <td>
                    {{word}}
                </td>
            {% endfor %}
        </tr>
    </table>
    <table id="showtable">
       <tr><td>
        <span id="showword"><font color=white>Your word : {{selected.ch}}</font></span>
       </td></tr>
    </table>
    <div>
        <input type="button" name="send" id="send" value="submit" onclick='javascript:document.getElementById("position").value=values;javascript:document.getElementById("submitform").submit();'>
        <input type="button" name="reset" id="reset" value="reset" onclick='javascript:document.getElementById("type").value="reset";document.getElementById("submitform").submit();document.getElementById("value")="";'>
    </div>
    <table bgcolor=white align="center" id="gametable" border="1">
        <form name="WHtable">
            <div id="check">
                {% for row in rows %}
                    <tr>
                        {% for char in row %}
                            <td>
                                <span id="p_{{ char.posX }}_{{ char.posY }}">
                                    <input type="button" {% if char.blue == 1 %}style="color:#0000FF;"{% elif char.isAns == 2 %}style="color:#00FF00;"{% elif char.isAns == 1 and cheat == 'yes' %}style="color:#FF0000;"{% endif %} value="{{ char.ch }}" name="{{ char.posX }}_{{ char.posY }}" id="b_{{ char.posX }}_{{ char.posY }}" onclick="javascript:check(name, value)">
                                </span>
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </div>
        </form>
    </table>
{% endif %}
</div>
</body>
<form id="submitform" name="submitform" method="POST">
    <input type="hidden" name="type" id="type" value="submit">
    <input type="hidden" name="val" id="val" value="{{selected.ch}}">
    <input type="hidden" name="platform" value="{% for row in rows %}{% for char in row %}{{char.ch}},{{char.posX}},{{char.posY}},{{char.isAns}}){% endfor %}/{% endfor %}">
    <input type="hidden" name="cheat" id="cheat" value="{{cheat}}">
    <input type="hidden" name="position" id="position" value="">
    <input type="hidden" name="quest" id="quest" value="{% for word in quest %}{{word}},{% endfor %}">
    <input type="hidden" name="mean" id="mean" value="{% for word in mean %}{{word}},{% endfor %}">
    {% csrf_token %}
</form>
</html>